# Generated by Django 2.2.6 on 2019-10-29 22:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('cid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=15)),
                ('no_of_classes', models.IntegerField()),
                ('course_plan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Course_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('fid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('f_fname', models.CharField(max_length=10)),
                ('f_lname', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('area_of_interest', models.CharField(max_length=30)),
                ('btech', models.CharField(max_length=20)),
                ('mtech', models.CharField(max_length=20)),
                ('phd', models.CharField(max_length=20)),
                ('house_no', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Faculty_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('sid', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_studentID', message='ID should be of form e.g 19CO101', regex='^[0-9]{2}[A-Z]{2}[0-9]{3}$')])),
                ('s_fname', models.CharField(max_length=15)),
                ('s_lname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}$')])),
                ('degree', models.CharField(max_length=20)),
                ('house_no', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6}$')])),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Student_Info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.StudentInfo')),
                ('date', models.DateField(db_column='Date')),
                ('attendance', models.CharField(max_length=3)),
                ('reason_for_absence', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Course_Attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.StudentInfo')),
            ],
            options={
                'db_table': 'Course_Registration',
                'managed': False,
            },
        ),
    ]
